// Database table types (will be generated by Supabase CLI)
export interface Database {
  public: {
    Tables: {
      goals: {
        Row: {
          id: string;
          user_id: string;
          title: string;
          description: string | null;
          target_date: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          title: string;
          description?: string | null;
          target_date?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          title?: string;
          description?: string | null;
          target_date?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      tasks: {
        Row: {
          id: string;
          goal_id: string;
          user_id: string;
          title: string;
          description: string | null;
          due_date: string | null;
          is_recurring: boolean;
          cadence: string | null;
          completed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          goal_id: string;
          user_id: string;
          title: string;
          description?: string | null;
          due_date?: string | null;
          is_recurring?: boolean;
          cadence?: string | null;
          completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          goal_id?: string;
          user_id?: string;
          title?: string;
          description?: string | null;
          due_date?: string | null;
          is_recurring?: boolean;
          cadence?: string | null;
          completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      streaks: {
        Row: {
          user_id: string;
          current_streak: number;
          best_streak: number;
          last_activity: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          current_streak?: number;
          best_streak?: number;
          last_activity?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          user_id?: string;
          current_streak?: number;
          best_streak?: number;
          last_activity?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      chat_sessions: {
        Row: {
          id: string;
          user_id: string;
          title: string | null;
          last_message_at: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          title?: string | null;
          last_message_at?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          title?: string | null;
          last_message_at?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      chat_messages: {
        Row: {
          id: string;
          session_id: string;
          user_id: string;
          role: "user" | "assistant";
          content: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          session_id: string;
          user_id: string;
          role: "user" | "assistant";
          content: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          session_id?: string;
          user_id?: string;
          role?: "user" | "assistant";
          content?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      get_today_tasks: {
        Args: {
          user_uuid: string;
        };
        Returns: {
          id: string;
          title: string;
          description: string | null;
          due_date: string | null;
          is_recurring: boolean;
          cadence: string | null;
          completed_at: string | null;
          goal_title: string;
        }[];
      };
      get_user_streak: {
        Args: {
          user_uuid: string;
        };
        Returns: {
          current_streak: number;
          best_streak: number;
          last_activity: string | null;
        }[];
      };
      update_streak: {
        Args: Record<PropertyKey, never>;
        Returns: undefined;
      };
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
}

// Helper types for easier access
export type DbGoal = Database["public"]["Tables"]["goals"]["Row"];
export type DbTask = Database["public"]["Tables"]["tasks"]["Row"];
export type DbStreak = Database["public"]["Tables"]["streaks"]["Row"];
export type DbChatSession =
  Database["public"]["Tables"]["chat_sessions"]["Row"];
export type DbChatMessage =
  Database["public"]["Tables"]["chat_messages"]["Row"];

export type InsertGoal = Database["public"]["Tables"]["goals"]["Insert"];
export type InsertTask = Database["public"]["Tables"]["tasks"]["Insert"];
export type InsertStreak = Database["public"]["Tables"]["streaks"]["Insert"];
export type InsertChatSession =
  Database["public"]["Tables"]["chat_sessions"]["Insert"];
export type InsertChatMessage =
  Database["public"]["Tables"]["chat_messages"]["Insert"];

export type DbUpdateGoal = Database["public"]["Tables"]["goals"]["Update"];
export type DbUpdateTask = Database["public"]["Tables"]["tasks"]["Update"];
export type DbUpdateStreak = Database["public"]["Tables"]["streaks"]["Update"];
export type DbUpdateChatSession =
  Database["public"]["Tables"]["chat_sessions"]["Update"];
export type DbUpdateChatMessage =
  Database["public"]["Tables"]["chat_messages"]["Update"];

// Function return types
export type TodayTask =
  Database["public"]["Functions"]["get_today_tasks"]["Returns"][0];
export type UserStreak =
  Database["public"]["Functions"]["get_user_streak"]["Returns"][0];

// Supabase client types
export interface SupabaseAuthUser {
  id: string;
  email?: string;
  created_at: string;
  updated_at: string;
}
